const app= require('express')
const { cargarActividades, cargahome, cargarForos, cargarFormularioCultivos, cargaformularioCosechas, cargaInformacionCultivo, preparacionTerreno, siembra, fertilizacion, enfermedades, produccion, venta, cargalogin }=require('../Controllers/CargaControllers')
const { agregarPost, leerPublicaciones, prepararTerreno, crearSiembra, crearFertilizacion, crearEnfermedad, crearProduccion, crearVentas, leerForos } = require('../Controllers/HomeControllers')
const Verificaruser = require('../Middleware/Verificaruser')
const { insertarCosecha, insertarPlantacion, obtenerCosechas, obtenerPlantaciones, insertarCultivo, obtenerTodasTablas,descargarInforme } = require('../Controllers/ActividadesControllers')
const router=app.Router()

router.get('/', cargalogin)
router.get('/descargarInforme',Verificaruser,descargarInforme);
router.get('/principal',Verificaruser,cargahome)
router.get('/publicandoymas',Verificaruser,leerPublicaciones)
router.get('/Acciones',Verificaruser,cargarActividades)
router.get('/Foros',Verificaruser,leerForos)
router.post('/principal',Verificaruser,agregarPost)
router.get('/yolo',Verificaruser,leerPublicaciones)
router.post('/cosecha',Verificaruser,insertarCosecha)
router.post('/agregarCultivo',Verificaruser,insertarCultivo)
router.get('/cosecha',Verificaruser,cargaformularioCosechas)
router.get('/agregarCultivo',Verificaruser,cargarFormularioCultivos)
router.get('/tablaCosecha',Verificaruser,obtenerCosechas)
router.get('/tablaCultivo',Verificaruser,obtenerPlantaciones)
router.get('/informacioCultivo',Verificaruser,cargaInformacionCultivo)
router.get('/preparacionTerreno',Verificaruser,preparacionTerreno)
router.get('/siembra',Verificaruser,siembra)
router.get('/fertilizacion',Verificaruser,fertilizacion)
router.get('/Enfermedades',Verificaruser,enfermedades)
router.get('/produccion',Verificaruser,produccion)
router.get('/venta',Verificaruser,venta)
router.get('/tablas',Verificaruser,obtenerTodasTablas)
router.get('/informe',Verificaruser,(req,res)=>{
    res.render('informe')
})
router.post('/publicandoymas',Verificaruser,agregarPost)
router.post('/preparacionTerreno',Verificaruser,prepararTerreno)
router.post('/siembra',Verificaruser,crearSiembra)
router.post('/fertilizacion',Verificaruser,crearFertilizacion)
router.post('/Enfermedades',Verificaruser,crearEnfermedad)
router.post('/produccion',Verificaruser,crearProduccion)
router.post('/venta',Verificaruser,crearVentas)
module.exports= router
